name: structured_project_flutter
description: A new Flutter project.
# Created in Flutter 3.0.2
# Release Command for web: flutter build web --web-renderer html --release

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10
  firebase_messaging: ^11.4.2
  firebase_crashlytics: ^2.8.2
  connectivity_plus: ^2.3.5
  dio: ^4.0.6
  google_fonts: ^3.0.1
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.1.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#f93523"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
